# Form implementation generated from reading ui file '/media/martokk/FILES/dev/apps/python/folder_structure_sync/assets/ui/pyqt5_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 607)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStatusTip("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QVBoxLayout()
        self.header.setSpacing(6)
        self.header.setObjectName("header")
        self.headerHorizontalLayout = QtWidgets.QHBoxLayout()
        self.headerHorizontalLayout.setObjectName("headerHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.headerHorizontalLayout.addItem(spacerItem)
        self.header_icon = QtWidgets.QLabel(self.centralwidget)
        self.header_icon.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_icon.sizePolicy().hasHeightForWidth())
        self.header_icon.setSizePolicy(sizePolicy)
        self.header_icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.header_icon.setScaledContents(True)
        self.header_icon.setWordWrap(False)
        self.header_icon.setObjectName("header_icon")
        self.headerHorizontalLayout.addWidget(self.header_icon)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.headerHorizontalLayout.addWidget(self.label)
        self.header_app_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.header_app_name.setFont(font)
        self.header_app_name.setObjectName("header_app_name")
        self.headerHorizontalLayout.addWidget(self.header_app_name)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.headerHorizontalLayout.addItem(spacerItem1)
        self.header.addLayout(self.headerHorizontalLayout)
        self.verticalLayout_2.addLayout(self.header)
        self.horizontalLine = QtWidgets.QFrame(self.centralwidget)
        self.horizontalLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontalLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalLine.setObjectName("horizontalLine")
        self.verticalLayout_2.addWidget(self.horizontalLine)
        self.script = QtWidgets.QWidget(self.centralwidget)
        self.script.setObjectName("script")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.script)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.source_browse_button = QtWidgets.QPushButton(self.script)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.source_browse_button.setIcon(icon)
        self.source_browse_button.setObjectName("source_browse_button")
        self.gridLayout.addWidget(self.source_browse_button, 0, 3, 1, 1)
        self.destination_line_edit = QtWidgets.QLineEdit(self.script)
        self.destination_line_edit.setObjectName("destination_line_edit")
        self.gridLayout.addWidget(self.destination_line_edit, 1, 2, 1, 1)
        self.source_label = QtWidgets.QLabel(self.script)
        self.source_label.setObjectName("source_label")
        self.gridLayout.addWidget(self.source_label, 0, 1, 1, 1)
        self.destination_label = QtWidgets.QLabel(self.script)
        self.destination_label.setObjectName("destination_label")
        self.gridLayout.addWidget(self.destination_label, 1, 1, 1, 1)
        self.source_line_edit = QtWidgets.QLineEdit(self.script)
        self.source_line_edit.setObjectName("source_line_edit")
        self.gridLayout.addWidget(self.source_line_edit, 0, 2, 1, 1)
        self.destination_browse_button = QtWidgets.QPushButton(self.script)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.destination_browse_button.setIcon(icon)
        self.destination_browse_button.setObjectName("destination_browse_button")
        self.gridLayout.addWidget(self.destination_browse_button, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.script)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scan_recursively_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.scan_recursively_checkbox.setObjectName("scan_recursively_checkbox")
        self.verticalLayout.addWidget(self.scan_recursively_checkbox)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.groupBox)
        self.ignoreFoldersGroupBox = QtWidgets.QGroupBox(self.script)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignoreFoldersGroupBox.sizePolicy().hasHeightForWidth())
        self.ignoreFoldersGroupBox.setSizePolicy(sizePolicy)
        self.ignoreFoldersGroupBox.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.ignoreFoldersGroupBox.setObjectName("ignoreFoldersGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ignoreFoldersGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.folder_to_ignore_list_widget = QtWidgets.QListWidget(self.ignoreFoldersGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.folder_to_ignore_list_widget.sizePolicy().hasHeightForWidth()
        )
        self.folder_to_ignore_list_widget.setSizePolicy(sizePolicy)
        self.folder_to_ignore_list_widget.setMaximumSize(QtCore.QSize(16777215, 99))
        self.folder_to_ignore_list_widget.setObjectName("folder_to_ignore_list_widget")
        self.verticalLayout_6.addWidget(self.folder_to_ignore_list_widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.folder_to_ignore_line_edit = QtWidgets.QLineEdit(self.ignoreFoldersGroupBox)
        self.folder_to_ignore_line_edit.setObjectName("folder_to_ignore_line_edit")
        self.horizontalLayout_2.addWidget(self.folder_to_ignore_line_edit)
        self.folder_to_ignore_add_button = QtWidgets.QPushButton(self.ignoreFoldersGroupBox)
        self.folder_to_ignore_add_button.setObjectName("folder_to_ignore_add_button")
        self.horizontalLayout_2.addWidget(self.folder_to_ignore_add_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addWidget(self.ignoreFoldersGroupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.script)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem6)
        self.run_script_button = QtWidgets.QPushButton(self.script)
        icon = QtGui.QIcon.fromTheme("text-x-script")
        self.run_script_button.setIcon(icon)
        self.run_script_button.setObjectName("run_script_button")
        self.horizontalLayout_4.addWidget(self.run_script_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.script)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.script_output = QtWidgets.QGroupBox(self.script)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script_output.sizePolicy().hasHeightForWidth())
        self.script_output.setSizePolicy(sizePolicy)
        self.script_output.setObjectName("script_output")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.script_output)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.script_output_text_edit = QtWidgets.QPlainTextEdit(self.script_output)
        self.script_output_text_edit.setObjectName("script_output_text_edit")
        self.verticalLayout_3.addWidget(self.script_output_text_edit)
        self.verticalLayout_4.addWidget(self.script_output)
        self.verticalLayout_2.addWidget(self.script)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1000)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 19))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMain = QtWidgets.QAction(MainWindow)
        self.actionMain.setObjectName("actionMain")
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.actionCustom = QtWidgets.QAction(MainWindow)
        self.actionCustom.setObjectName("actionCustom")
        self.menuAbout.addAction(self.about_action)
        self.menuAbout.addAction(self.actionCustom)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header_icon.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><img src=":/resources/icon" height="64" width="64" /></p></body></html>',
            )
        )
        self.header_app_name.setText(_translate("MainWindow", "Workflow Manager v1.0"))
        self.source_browse_button.setText(_translate("MainWindow", "Browse"))
        self.source_label.setText(_translate("MainWindow", "Source"))
        self.destination_label.setText(_translate("MainWindow", "Destination"))
        self.destination_browse_button.setText(_translate("MainWindow", "Browse"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.scan_recursively_checkbox.setText(_translate("MainWindow", "Serch Recursively"))
        self.ignoreFoldersGroupBox.setTitle(_translate("MainWindow", "Folders to Ignore"))
        self.folder_to_ignore_add_button.setText(_translate("MainWindow", "Add"))
        self.run_script_button.setText(_translate("MainWindow", "Run Script"))
        self.script_output.setTitle(_translate("MainWindow", "Script Output:"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionMain.setText(_translate("MainWindow", "Main"))
        self.about_action.setText(_translate("MainWindow", "About"))
        self.actionCustom.setText(_translate("MainWindow", "Get more custom scripts..."))


import resources_rc


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
